chain=liquidregtest
[liquidregtest]
rpcuser=lquser1
rpcpassword=lqpass1
rpcport=12001
port=13001
bind=127.0.0.1
connect=127.0.0.1:13002

daemon=1
listen=1
txindex=1 # enable txindex for electrs
discover=0
listenonion=0
shrinkdebugfile=0

initialfreecoins=2100000000000000
anyonecanspendaremine=1 # enable anyone can spend
fallbackfee=0.000001
creatediscountct=1 # enable discount, otherwise transactions cannot pass minimum fee requirements

validatepegin=0 # disable peg-in, standalone chain not need peg-in and peg-out
fdefaultconsistencychecks=0 # default consistency checks, ensure chain state integrity (usually set to 1 in testing, but set to 0 in production to improve performance)
evbparams=dynafed:0::60:60
con_max_block_sig_size=2000

signblockscript=522103132cabec6b0334a7cb388bcf178a85a1f366ee3d7b747e1b7bf16cfff40b45042102726b2b67ee1411baeb09e8122619d3e029af9bb8b6665609285bb5435f844f9152ae
